version: '3.8'
services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=posts'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
    networks:
      - spring-boot-project
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  spring-boot-project:
    name: spring-boot-project
    driver: bridge
