services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=posts'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - spring-boot-project

networks:
  spring-boot-project:
    name: spring-boot-project
    driver: bridge
